export const WORKOUT_REPOSITORY = Symbol ('WORKOUT_REPOSITORY');
export const EXERCISE_REPOSITORY = Symbol ('EXERCISE_REPOSITORY');
export const WORKOUTEXERCISE_REPOSITORY
            = Symbol('WORKOUT_EXERCISE_REPOSITORY');